---
name: "Docker Pipeline"

on:
  push:
    branches:
      - "**"
    tags:
      - "*.*.*"
  pull_request:

env:
  TERM: xterm
  # enable Docker push only if the required secrets are defined
  ENABLE_DOCKER_PUSH: ${{ secrets.DOCKERHUB_USER != null && secrets.DOCKERHUB_TOKEN != null }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # Set Docker image
      - name: Set up Docker repository
        run: echo "DOCKERHUB_REPO=$( if [[ -n $USER_REPO ]]; then echo $USER_REPO; else echo $GITHUB_REPOSITORY; fi )" >> $GITHUB_ENV
        env:
          USER_REPO: ${{ secrets.DOCKERHUB_REPO }}

      - name: Set software version
        run: |
          sw_version=$(jq -r ".version" package.json)
          echo "SOFTWARE_VERSION=${sw_version}" >> $GITHUB_ENV
          echo ::set-output name=sw_version::${sw_version}

      # Extract Docker metadata
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=${{ env.SOFTWARE_VERSION }}
            type=raw,value=${{ env.SOFTWARE_VERSION}}.build${{ github.run_number }}
            type=sha
          labels: |
            org.opencontainers.image.version=${{ env.SOFTWARE_VERSION }}.build${{ github.run_number }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # DockerHub Login
      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: ${{ env.ENABLE_DOCKER_PUSH == 'true' }}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push
      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: ${{ env.ENABLE_DOCKER_PUSH == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
